version: '3'

services:
   db:
      image: mysql
      env_file:
         - ./.env
      cap_add:
         - SYS_NICE
      command:
         - --default-authentication-plugin=mysql_native_password
         - --sort_buffer_size=512000000
         - --lower_case_table_names=1
      volumes:
         - ./data/:/var/lib/mysql/
      restart: always

   adminer:
      image: adminer
      env_file:
         - ./.env
      ports:
         - 9002:8080
      restart: always

   back:
      build: ./back/
      env_file:
         - ./.env
      command: sh -c '/wait-for db:3306 -t 30 -- npm run start'
      volumes:
         - ./back/src/:/app/src/
      ports:
         - 9001:9001
      restart: always

   front:
      build:
         context: ./front/
         dockerfile: ./Dockerfile
      ports:
         - 80:80
      restart: always
